// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPF_Budgetplanerare_GOhman.Data;

#nullable disable

namespace WPF_Budgetplanerare_GOhman.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207165903_MoreSeeding")]
    partial class MoreSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WPF_Budgetplanerare_GOhman.Models.BudgetTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRecurrence")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RecurringRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BudgetTransactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Amount = 5000m,
                            Category = 6,
                            EffectiveDate = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurrence = false,
                            IsRecurring = false,
                            Note = "Övertid",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Amount = 1200m,
                            Category = 2,
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurrence = false,
                            IsRecurring = true,
                            Note = "Hyra",
                            RecurringRuleId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Amount = 800m,
                            Category = 0,
                            EffectiveDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurrence = false,
                            IsRecurring = false,
                            Note = "Mat",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Amount = 400m,
                            Category = 3,
                            EffectiveDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurrence = false,
                            IsRecurring = false,
                            Note = "Transport",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Amount = 300m,
                            Category = 1,
                            EffectiveDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurrence = false,
                            IsRecurring = false,
                            Note = "Elräkning",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Amount = 200m,
                            Category = 2,
                            EffectiveDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurrence = false,
                            IsRecurring = true,
                            Note = "Hemförsäkring",
                            RecurringRuleId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Amount = 1500m,
                            Category = 8,
                            EffectiveDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurrence = false,
                            IsRecurring = false,
                            Note = "Frilansjobb",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Amount = 600m,
                            Category = 4,
                            EffectiveDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurrence = false,
                            IsRecurring = false,
                            Note = "Underhållning",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Amount = 1000m,
                            Category = 9,
                            EffectiveDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurrence = false,
                            IsRecurring = false,
                            Note = "Sparande",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Amount = 2500m,
                            Category = 9,
                            EffectiveDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurrence = false,
                            IsRecurring = true,
                            Note = "Årsbonus",
                            RecurringRuleId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),
                            Amount = 450m,
                            Category = 4,
                            EffectiveDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurrence = false,
                            IsRecurring = true,
                            Note = "Gymkort",
                            RecurringRuleId = new Guid("eeeeeeee-aaaa-bbbb-cccc-dddddddddddd"),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("cccccccc-dddd-eeee-ffff-111111111111"),
                            Amount = 900m,
                            Category = 0,
                            EffectiveDate = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurrence = false,
                            IsRecurring = false,
                            Note = "Matinköp",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("dddddddd-eeee-ffff-1111-222222222222"),
                            Amount = 350m,
                            Category = 1,
                            EffectiveDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurrence = false,
                            IsRecurring = true,
                            Note = "Internetabonnemang",
                            RecurringRuleId = new Guid("11111111-aaaa-bbbb-cccc-ffffffffffff"),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-ffff-1111-2222-333333333333"),
                            Amount = 120m,
                            Category = 1,
                            EffectiveDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurrence = false,
                            IsRecurring = true,
                            Note = "Mobilabonnemang",
                            RecurringRuleId = new Guid("22222222-aaaa-bbbb-cccc-ffffffffffff"),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("ffffffff-1111-2222-3333-444444444444"),
                            Amount = 700m,
                            Category = 9,
                            EffectiveDate = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurrence = false,
                            IsRecurring = false,
                            Note = "Kläder",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555555"),
                            Amount = 1600m,
                            Category = 8,
                            EffectiveDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurrence = false,
                            IsRecurring = false,
                            Note = "Frilansprojekt",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-3333-4444-5555-666666666666"),
                            Amount = 500m,
                            Category = 3,
                            EffectiveDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurrence = false,
                            IsRecurring = false,
                            Note = "Resa till Stockholm",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-4444-5555-6666-777777777777"),
                            Amount = 300m,
                            Category = 4,
                            EffectiveDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurrence = false,
                            IsRecurring = false,
                            Note = "Biobiljetter",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-5555-6666-7777-888888888888"),
                            Amount = 2000m,
                            Category = 9,
                            EffectiveDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurrence = false,
                            IsRecurring = true,
                            Note = "Sommarbonus",
                            RecurringRuleId = new Guid("ffffffff-bbbb-cccc-dddd-eeeeeeeeeeee"),
                            TransactionType = 0
                        });
                });

            modelBuilder.Entity("WPF_Budgetplanerare_GOhman.Models.RecurrenceException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecurringRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecurringRuleId");

                    b.ToTable("RecurrenceExceptions");
                });

            modelBuilder.Entity("WPF_Budgetplanerare_GOhman.Models.RecurringRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BudgetTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BudgetTransactionId")
                        .IsUnique();

                    b.ToTable("RecurringRules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            BudgetTransactionId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Frequency = 0,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            BudgetTransactionId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Frequency = 1,
                            StartDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            BudgetTransactionId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Frequency = 0,
                            StartDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-aaaa-bbbb-cccc-dddddddddddd"),
                            BudgetTransactionId = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),
                            Frequency = 0,
                            StartDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ffffffff-bbbb-cccc-dddd-eeeeeeeeeeee"),
                            BudgetTransactionId = new Guid("44444444-5555-6666-7777-888888888888"),
                            Frequency = 1,
                            StartDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("11111111-aaaa-bbbb-cccc-ffffffffffff"),
                            BudgetTransactionId = new Guid("dddddddd-eeee-ffff-1111-222222222222"),
                            Frequency = 0,
                            StartDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("22222222-aaaa-bbbb-cccc-ffffffffffff"),
                            BudgetTransactionId = new Guid("eeeeeeee-ffff-1111-2222-333333333333"),
                            Frequency = 0,
                            StartDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WPF_Budgetplanerare_GOhman.Models.RecurrenceException", b =>
                {
                    b.HasOne("WPF_Budgetplanerare_GOhman.Models.RecurringRule", "RecurringRule")
                        .WithMany("RecurrenceExceptions")
                        .HasForeignKey("RecurringRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecurringRule");
                });

            modelBuilder.Entity("WPF_Budgetplanerare_GOhman.Models.RecurringRule", b =>
                {
                    b.HasOne("WPF_Budgetplanerare_GOhman.Models.BudgetTransaction", "BudgetTransaction")
                        .WithOne("RecurringRule")
                        .HasForeignKey("WPF_Budgetplanerare_GOhman.Models.RecurringRule", "BudgetTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetTransaction");
                });

            modelBuilder.Entity("WPF_Budgetplanerare_GOhman.Models.BudgetTransaction", b =>
                {
                    b.Navigation("RecurringRule");
                });

            modelBuilder.Entity("WPF_Budgetplanerare_GOhman.Models.RecurringRule", b =>
                {
                    b.Navigation("RecurrenceExceptions");
                });
#pragma warning restore 612, 618
        }
    }
}
